[build]
  publish = "public/"
  command = "gatsby build"
  functions = "functions/"

[dev]
  command = "npm start"
  functions = "functions/"
  framework = "#custom"
  port = 14141 
  targetPort = 1414
  publish = "public/"